---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
     name: "{{myjavapackonubuntu}}"
     state: present
    when: ansible_os_family=="Debian"
  - name: install java on amazon
    apt:
     name: "{{myjavapackonamazon}}"
     state: present
    when: ansible_os_family=="Redhat"
