---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: I want to install apache2 webserver on ubuntu nodes
    apt: 
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family=="Debian" 

  - name: I want to start apache2 webserver on ubuntu
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family=="Debian"

  - name: I want to install httpd webserver on redhat nodes
    dnf:
      name: "{{mywebpackonamazon}}"
      state: present
    when: ansible_os_family=="RedHat"

  - name: I want to start httpd webserver on Redhat nodes
    service:
      name: "{{mywebpackonamazon}}"
      state: started
    when: ansible_os_family=="RedHat"
