---
 - name: grant tomcat ownership on tomcat folder
   command: sudo chown -R tomcat:tomcat /opt/tomcat/
 - name: grant execute permission on bin folder
   command: sudo chmod -R u+x /opt/tomcat/bin
